window.SSNGamesCatalog = [
  {"id":"quickcall","title":"Quick Call","category":"Party","description":"Wait for your name, type your random code, and race for the fastest reply.","command":"!quick","path":"games/quickcall.html","image":"images/games/quickcall.jpg","demo":true,"audience":"Solo-friendly"},
  {
    "id": "mazeraid",
    "title": "Maze Raid",
    "category": "Party",
    "description": "Chat becomes avatar raiders in a full-window, auto-roaming retro maze.",
    "command": "Say anything in chat",
    "path": "games/mazeraid.html",
    "image": "images/games/mazeraid.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "fireflycatch",
    "title": "Firefly Catch",
    "category": "Puzzle",
    "description": "Time your catches as glowing fireflies cross a transparent OBS overlay.",
    "command": "!catch",
    "path": "games/fireflycatch.html",
    "image": "images/games/fireflycatch.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "cometrally",
    "title": "Comet Rally",
    "category": "Teams",
    "description": "Boost your team comet along a transparent race track at the bottom of your stream.",
    "command": "!boost",
    "path": "games/cometrally.html",
    "image": "images/games/cometrally.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "signallock",
    "title": "Signal Lock",
    "category": "Puzzle",
    "description": "Crack a shared four-digit code using clues from every guess.",
    "command": "!code 1234",
    "path": "games/signallock.html",
    "image": "images/games/signallock.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "crowdquest",
    "title": "Crowd Quest",
    "category": "Cooperative",
    "description": "Vote on the route of a five-stop space adventure.",
    "command": "!vote 2",
    "path": "games/crowdquest.html",
    "image": "images/games/crowdquest.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "minorityclub",
    "title": "Minority Club",
    "category": "Party",
    "description": "Pick a symbol and try to land in the smallest group.",
    "command": "!pick sun",
    "path": "games/minorityclub.html",
    "image": "images/games/minorityclub.jpg",
    "demo": true,
    "audience": "3+ chatters"
  },
  {
    "id": "tugofwar",
    "title": "Tug of War",
    "category": "Teams",
    "description": "Answer word and math prompts to pull your monster team to victory.",
    "command": "!join",
    "path": "games/tugofwar.html",
    "image": "images/games/tugofwar.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "crewkitchen",
    "title": "Crew Kitchen",
    "category": "Cooperative",
    "description": "Contribute ingredients to finish four shared cooking orders.",
    "command": "!cook tomato",
    "path": "games/crewkitchen.html",
    "image": "images/games/crewkitchen.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "beaconrelay",
    "title": "Beacon Relay",
    "category": "Cooperative",
    "description": "Take turns passing a light through twenty stops.",
    "command": "!pass",
    "path": "games/beaconrelay.html",
    "image": "images/games/beaconrelay.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "meteorshield",
    "title": "Meteor Shield",
    "category": "Cooperative",
    "description": "Coordinate colored shields to protect a ship from meteors.",
    "command": "!shield red",
    "path": "games/meteorshield.html",
    "image": "images/games/meteorshield.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "memoryparade",
    "title": "Memory Parade",
    "category": "Puzzle",
    "description": "Remember longer sequences of colored numbers each round.",
    "command": "!ready",
    "path": "games/memoryparade.html",
    "image": "images/games/memoryparade.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "oddoneout",
    "title": "Odd One Out",
    "category": "Puzzle",
    "description": "Answer quick multiple-choice questions where everyone can score.",
    "command": "!odd 1",
    "path": "games/oddoneout.html",
    "image": "images/games/oddoneout.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "sumsquad",
    "title": "Sum Squad",
    "category": "Cooperative",
    "description": "Take turns adding numbers to reach three exact shared targets.",
    "command": "!add 5",
    "path": "games/sumsquad.html",
    "image": "images/games/sumsquad.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "rockpapershowdown",
    "title": "Rock Paper Showdown",
    "category": "Party",
    "description": "Choose your move and try to beat the hidden house choice.",
    "command": "!throw rock",
    "path": "games/rockpapershowdown.html",
    "image": "images/games/rockpapershowdown.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "wordshuffle",
    "title": "Word Shuffle",
    "category": "Puzzle",
    "description": "Unscramble the letters before the clock runs out.",
    "command": "!solve lantern",
    "path": "games/wordshuffle.html",
    "image": "images/games/wordshuffle.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "numberhunt",
    "title": "Number Hunt",
    "category": "Puzzle",
    "description": "Narrow the range together to find a hidden number.",
    "command": "!guess 50",
    "path": "games/numberhunt.html",
    "image": "images/games/numberhunt.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "spampower",
    "title": "Spam Power",
    "category": "Party",
    "description": "Power a shared goal with chat activity.",
    "command": "Hello crew!",
    "path": "games.html",
    "image": "images/games/spampower.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "battlefield",
    "title": "Battlefield Mayhem",
    "category": "Teams",
    "description": "Join as a fighter and watch an automatic arena battle.",
    "command": "!join",
    "path": "battle.html",
    "image": "images/games/battlefield.jpg",
    "demo": false,
    "audience": "2+ chatters"
  },
  {
    "id": "emojirain",
    "title": "Emoji Rain",
    "category": "Creative",
    "description": "Turn the emojis in chat into a colorful downpour.",
    "command": "Use emojis in chat",
    "path": "games/emojirain.html",
    "image": "images/games/emojirain.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "chatwars",
    "title": "Chat Wars",
    "category": "Teams",
    "description": "Join a color team and help capture the map.",
    "command": "!red",
    "path": "games/chatwars.html",
    "image": "images/games/chatwars.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "wordstorm",
    "title": "Word Storm",
    "category": "Creative",
    "description": "Grow a swirling word cloud from what chat is saying.",
    "command": "community sparkle rocket",
    "path": "games/wordstorm.html",
    "image": "images/games/wordstorm.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "chaosmode",
    "title": "Chaos Mode",
    "category": "Creative",
    "description": "Build visual chaos as chat activity rises.",
    "command": "party chaos boom",
    "path": "games/chaosmode.html",
    "image": "images/games/chaosmode.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "colorsymphony",
    "title": "Color Symphony",
    "category": "Creative",
    "description": "Paint musical color effects by naming colors in chat.",
    "command": "red blue green",
    "path": "games/colorsymphony.html",
    "image": "images/games/colorsymphony.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "chatgarden",
    "title": "Chat Garden",
    "category": "Creative",
    "description": "Grow a shared garden by mentioning flowers and plants.",
    "command": "flower rose tree",
    "path": "games/chatgarden.html",
    "image": "images/games/chatgarden.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "pixelbattle",
    "title": "Pixel Battle",
    "category": "Creative",
    "description": "Paint a collaborative pixel canvas with chat coordinates.",
    "command": "red 3 4",
    "path": "games/pixelbattle.html",
    "image": "images/games/pixelbattle.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "memorylane",
    "title": "Memory Lane",
    "category": "Creative",
    "description": "Turn shared memories and nostalgic messages into a visual collage.",
    "command": "I remember childhood school friends",
    "path": "games/memorylane.html",
    "image": "images/games/memorylane.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "rhythmpulse",
    "title": "Rhythm Pulse",
    "category": "Creative",
    "description": "Trigger rhythm effects with beat and instrument words.",
    "command": "kick snare boom",
    "path": "games/rhythmpulse.html",
    "image": "images/games/rhythmpulse.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "petrace",
    "title": "Pet Race",
    "category": "Party",
    "description": "Enter an animal racer and cheer it toward the finish.",
    "command": "!join dog",
    "path": "games/petrace.html",
    "image": "images/games/petrace.jpg",
    "demo": true,
    "audience": "3+ chatters"
  },
  {
    "id": "wordchain",
    "title": "Word Chain",
    "category": "Puzzle",
    "description": "Continue a word chain using the last letter of the previous word.",
    "command": "ORANGE",
    "path": "games/wordchain.html",
    "image": "images/games/wordchain.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "emojitower",
    "title": "Emoji Tower",
    "category": "Cooperative",
    "description": "Stack chat emojis into a growing community tower.",
    "command": "!drop",
    "path": "games/emojitower.html",
    "image": "images/games/emojitower.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "colorwars",
    "title": "Color Wars",
    "category": "Teams",
    "description": "Paint territory for your chosen color team.",
    "command": "!red",
    "path": "games/colorwars.html",
    "image": "images/games/colorwars.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "treasurehunt",
    "title": "Treasure Hunt",
    "category": "Puzzle",
    "description": "Dig at grid coordinates to uncover buried treasure.",
    "command": "!dig A1",
    "path": "games/treasurehunt.html",
    "image": "images/games/treasurehunt.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "dancingparade",
    "title": "Dancing Parade",
    "category": "Creative",
    "description": "Join a parade of dancing characters along the screen.",
    "command": "!join",
    "path": "games/dancingparade.html",
    "image": "images/games/dancingparade.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  },
  {
    "id": "chickenroyale",
    "title": "Chicken Royale",
    "category": "Party",
    "description": "Enter a 3D chicken arena and try to be the last bird standing.",
    "command": "!join",
    "path": "games/chickenroyale.html",
    "image": "images/games/chickenroyale.jpg",
    "demo": true,
    "audience": "2+ chatters"
  },
  {
    "id": "phraseguess",
    "title": "Phrase Guessing",
    "category": "Puzzle",
    "description": "Guess the host's phrases as their letters are gradually revealed.",
    "command": "Guess the phrase",
    "path": "games/phraseguess.html",
    "image": "images/games/phraseguess.jpg",
    "demo": true,
    "audience": "Solo-friendly"
  }
];
