(function(){'use strict';
var params=new URLSearchParams(location.search),demo=params.has('demo'),game=new SSNQuickCall({now:function(){return performance.now();}}),connection=document.getElementById('connection'),paused=false,pausedAt=0,revision=-1;
if(demo)document.body.classList.add('demo');if(params.has('chroma'))document.body.classList.add('chroma');if(params.has('clean'))document.getElementById('controls').hidden=true;
function el(tag,value,cls){var e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e;}
function render(){document.getElementById('clock').textContent=paused?'PAUSED':game.phase==='waiting'?'JOIN IN':Math.max(0,Math.ceil((game.deadline-performance.now())/1000))+'s';if(revision===game.revision)return;revision=game.revision;
document.getElementById('round').textContent=game.phase==='waiting'?'Waiting for players':game.phase==='joining'?'Calling names shortly':'Call '+game.round;document.getElementById('queue').textContent=game.queue.length+' waiting';document.getElementById('instruction').textContent=game.phase==='result'?'Times are in! Next names coming up. Type !quick to join.':'Type !quick to join. Only reply when your name is called.';
var calls=document.getElementById('calls');calls.textContent='';game.calls.forEach(function(c){var row=el('article','','call'+(c.time!==null?' done':''));row.appendChild(el('span',c.name,'name'));row.appendChild(el('strong',c.code,'code'));row.appendChild(el('span',c.time!==null?(c.time/1000).toFixed(2)+'s - got it!':game.phase==='result'?'Missed - !quick to rejoin':'Your turn - type this code','outcome'));calls.appendChild(row);});if(!game.calls.length)calls.appendChild(el('p','Your name. Four characters. How quick are you?','empty'));
var leaders=document.getElementById('leaders');leaders.textContent='';game.leaders().forEach(function(p,i){var row=el('li','');row.appendChild(el('span',(i+1)+'. '+p.name));row.appendChild(el('b',(p.best/1000).toFixed(2)+'s'));leaders.appendChild(row);});if(!leaders.children.length)leaders.appendChild(el('li','Your first correct reply starts the leaderboard.'));
}
function receive(payload){if(paused)return;(Array.isArray(payload)?payload.slice(0,100):[payload]).forEach(function(m){if(m&&m.content)m=m.content;if(!m||typeof m.chatmessage!=='string'||m.chatmessage.length>2000)return;var copy=Object.assign({},m);if(!copy.textonly){var t=document.createElement('template');t.innerHTML=copy.chatmessage;copy.chatmessage=t.content.textContent||'';}if(game.input(copy)&&!demo)connection.textContent='Chat received';});render();}
document.getElementById('pause').onclick=function(){paused=!paused;if(paused)pausedAt=performance.now();else game.shiftTime(performance.now()-pausedAt);this.textContent=paused?'Resume':'Pause';render();};document.getElementById('restart').onclick=function(){game.reset();revision=-1;if(paused)pausedAt=performance.now();render();};setInterval(function(){if(!paused){game.tick();render();}},100);render();
if(demo){connection.textContent='Preview - simulated chat';['Juniper','Milo','Cosmic Cat','Nova','River'].forEach(function(name){receive({type:'demo',chatname:name,chatmessage:'!quick',textonly:true});});setInterval(function(){if(paused||game.phase!=='active')return;var c=game.calls.find(function(c){return c.time===null;});if(c)receive({type:'demo',chatname:c.name,chatmessage:c.code,textonly:true});},2700);return;}
var session=params.get('session')||params.get('room')||params.get('s')||params.get('id');if(!session){connection.textContent='Add your SSN session to connect';return;}
if(params.has('server')){var endpoint=params.get('server')||'wss://io.socialstream.ninja',socket,retry,closed=false;try{var parsed=new URL(endpoint);if(parsed.protocol!=='ws:'&&parsed.protocol!=='wss:')throw new Error();}catch(_){connection.textContent='Invalid relay address';return;}
 function connect(){if(closed)return;connection.textContent='Connecting to chat';try{socket=new WebSocket(endpoint);}catch(_){connection.textContent='Could not connect';return;}socket.onopen=function(){socket.send(JSON.stringify({join:session.split(',')[0],out:2,in:1}));connection.textContent='Relay connected - waiting for chat';};socket.onmessage=function(event){if(typeof event.data!=='string'||event.data.length>256000)return;try{receive(JSON.parse(event.data));}catch(_){}};socket.onerror=function(){socket.close();};socket.onclose=function(){if(!closed){connection.textContent='Reconnecting';retry=setTimeout(connect,5000);}};}
 window.addEventListener('beforeunload',function(){closed=true;clearTimeout(retry);if(socket)socket.close();});connect();return;
}
var bridge=document.createElement('iframe');bridge.title='SSN chat connection';bridge.style.cssText='position:fixed;width:0;height:0;border:0;left:-100px;top:-100px';bridge.src='https://vdo.socialstream.ninja/?ln&salt=vdo.ninja&notmobile&password='+encodeURIComponent(params.get('password')||'false')+'&solo&view='+encodeURIComponent(session)+'&novideo&noaudio&label=dock&cleanoutput&room='+encodeURIComponent(session);
window.addEventListener('message',function(event){if(event.source!==bridge.contentWindow)return;var data=event.data&&event.data.dataReceived;if(data&&data.overlayNinja)receive(data.overlayNinja);});document.body.appendChild(bridge);
})();
