'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const core = require('../shared/giveaway/core.js');
const rng = {getRandomValues: array => { array[0] = 0; return array; }};
const chat = (name, extra) => Object.assign({chatname:name, type:'youtube', chatmessage:'!enter'}, extra);
const pool = core.create({crypto:rng});
assert.equal(pool.ingest(chat('Avery')), false);
pool.command('startgiveaway');
assert.equal(pool.ingest(chat('Avery')), true);
assert.equal(pool.ingest(chat('AVERY')), false);
assert.equal(pool.ingest(chat('Avery', {type:'twitch'})), true);
assert.equal(pool.ingest(chat('Morgan', {chatmessage:'I want !enter'})), false);
for (const flag of ['bot','reflection','replay','history','reload','private','event']) assert.equal(pool.ingest(chat(flag,{[flag]:true})),false);
assert.equal(pool.command('drawgiveaway').winners[0].name, 'Avery');
assert.equal(pool.snapshot().open,false);
assert.equal(pool.snapshot().count,1);
pool.command('startgiveaway');
assert.equal(pool.ingest(chat('Avery')),false);
pool.command('drawgiveaway');
assert.equal(pool.snapshot().count,0);
assert.throws(() => pool.command('drawgiveaway'), /no eligible/);
pool.command('resetgiveaway');
assert.equal(pool.snapshot().winners.length,0);
assert.equal(pool.isOpen(),false);
pool.command('startgiveaway',{keyword:'!join',match:'word',membersOnly:true});
assert.equal(pool.ingest(chat('Morgan',{chatmessage:'hi !join',membership:'Member'})),true);
assert.equal(pool.ingest(chat('Sam',{chatmessage:'hi !join'})),false);
assert.equal(pool.ingest(chat('Sam',{chatmessage:'hi !joiner',membership:'Member'})),false);
assert.throws(() => pool.command('startgiveaway',{keyword:'oops',match:'invalid'}),/matching/);
assert.equal(pool.snapshot().keyword,'!join');
const repeated = core.create({crypto:rng});
repeated.command('startgiveaway',{removeWinner:false});
repeated.ingest(chat('Sam'));
repeated.command('drawgiveaway');
assert.equal(repeated.command('drawgiveaway').count,1);
assert.equal(repeated.snapshot().winners.length,2);
const insecure = core.create();
insecure.command('startgiveaway'); insecure.ingest(chat('Sam'));
assert.throws(() => insecure.command('drawgiveaway'),/Secure random/);
assert.equal(insecure.snapshot().winners.length,0);
let randomCalls=0;
const unbiased=core.create({crypto:{getRandomValues:a=>{a[0]=randomCalls++ ? 2 : 4294967295;}}});
unbiased.command('startgiveaway'); ['A','B','C'].forEach(n=>unbiased.ingest(chat(n)));
assert.equal(unbiased.command('drawgiveaway').winners[0].name,'C');
assert.equal(randomCalls,2);
// Durable host/session behavior is exercised with real IndexedDB in
// giveaway-economy.test.cjs and through the extension in giveaway-popup.test.cjs.
const router=require('../js/streamdeck-remote-control.js');
for(const action of ['startgiveaway','closegiveaway','drawgiveaway','resetgiveaway','getgiveawaystate']) assert.equal(router.SSN_ACTIONS[action],true);
assert.ok(fs.readFileSync('loader.js','utf8').indexOf('./shared/giveaway/core.js') < fs.readFileSync('loader.js','utf8').indexOf('./background.js'));
console.log('Legacy giveaway core and command registry tests passed');
