// Manual: node tests/ninjabacker-ssapp.e2e.cjs
// Runs the real NinjaBacker source against a temporary DB and SSApp profile.
// No live accounts, Stripe calls, payments, or outgoing chat messages.
const { _electron } = require('playwright');
const fs = require('fs'), os = require('os'), path = require('path'), assert = require('assert');
const { pathToFileURL } = require('url');
const crypto = require('crypto');
const root = path.resolve(__dirname, '..').replace(/\\/g, '/');
const ninja = process.env.SSN_TEST_NINJABACKER_ROOT || path.resolve(root, '../vdoninja/tip-server');
const ssapp = process.env.SSN_TEST_SSAPP_ROOT || path.resolve(root, '../ssapp');
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'ssn-ninja-e2e-'));
const room = 'ninjaqa' + Date.now();
process.env.TIP_DB_PATH = path.join(profile, 'tips.db');
process.env.STRIPE_SECRET_KEY = 'sk_test_isolated_ssn';
process.env.STRIPE_WEBHOOK_SECRET = 'whsec_isolated_ssn';
process.env.STRIPE_TEST_WEBHOOK_SECRET = '';
process.env.STRIPE_PUBLISHABLE_KEY = 'pk_test_isolated_ssn';
process.env.TEST_ACCOUNT_IDS = '';
process.env.DISCORD_WEBHOOK_URL = '';
fs.writeFileSync(path.join(profile, 'savedSync.json'), JSON.stringify({ streamID: room, password: 'false', state: false, settings: {}, wsServer: false }));

(async () => {
 const db = await import(pathToFileURL(path.join(ninja, 'db.js')).href);
 const { fastify: server } = await import(pathToFileURL(path.join(ninja, 'server.js')).href);
 const Stripe = require(path.join(ninja, 'node_modules/stripe'));
 const stripe = new Stripe(process.env.STRIPE_SECRET_KEY);
 db.initDatabase();
 const owner = db.createPerformer({ username: 'creator', email: 'ssn@example.invalid', stripeAccountId: 'acct_ssn_fixture' });
 const token = db.generateOverlayToken(owner.id, owner.username);
 db.updatePerformer(owner.id, { chargesEnabled: true, onboardingComplete: true });
 const session = db.createSession(owner.id);
 await server.listen({ host: '127.0.0.1', port: 0 });
 const port = server.server.address().port;
 const wrapper = path.join(profile, 'bootstrap.cjs');
 fs.writeFileSync(wrapper, `const {app}=require('electron');app.setAppPath(${JSON.stringify(ssapp)});app.on('session-created',s=>s.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*','ws://*/*','wss://*/*']},(d,cb)=>{const h=new URL(d.url).hostname;cb({cancel:!['localhost','127.0.0.1','vdo.socialstream.ninja','wss.socialstream.ninja','vdo.ninja'].includes(h)});}));require(${JSON.stringify(path.join(ssapp, 'bootstrap.js'))});`);
 const { createServer } = await import(pathToFileURL(path.join(root, 'monetization-server/server.js')).href);
 const Database = require(path.join(root, 'monetization-server/node_modules/better-sqlite3'));
 const receiverPath = path.join(profile, 'receiver.db'), masterKey = crypto.randomBytes(32);
 let receiver, receiverDb, receiverPort = 0;
 async function startReceiver() {
  receiverDb = new Database(receiverPath);
  receiver = await createServer({ ninja: { db: receiverDb, masterKey, fetch: url => fetch('http://127.0.0.1:' + port + new URL(url).pathname) } });
  await receiver.listen({ host: '127.0.0.1', port: receiverPort });
  receiverPort = receiver.server.address().port;
 }
 await startReceiver();
 let app;
 try {
  app = await _electron.launch({ executablePath: path.join(ssapp, 'node_modules/electron/dist/electron.exe'), args: [wrapper, '--running-from-source', '--multiinstance', '--ssapp-headless-control', '--filesource', 'file:///' + root + '/', '--no-hwa'], cwd: ssapp, env: { ...process.env, SSAPP_USER_DATA_DIR: profile, SSAPP_DIAGNOSTICS_SAFE_GPU: '1' } });
  const main = await app.firstWindow();
  main.setDefaultTimeout(25000);
  await main.waitForFunction(() => document.querySelector('#frame2')?.contentWindow?.handleMonetizationRequest);
  const bg = main.frames().find(f => /background\.html/.test(f.url()));
  const popup = main.frames().find(f => /popup\.html/.test(f.url()));
  const request = data => popup.evaluate(data => new Promise(resolve => chrome.runtime.sendMessage(data, resolve)), data);
  await bg.evaluate(({ port, receiverPort }) => {
   const originalFetch = fetch, OriginalSource = EventSource, originalProcess = processIncomingMessage;
   function local(url) { const u = new URL(url); return 'http://127.0.0.1:' + (u.hostname === 'api.socialstream.ninja' ? receiverPort : port) + u.pathname + u.search; }
   window.fetch = (url, options) => originalFetch(/^https:\/\/(ninjabacker.com|api.socialstream.ninja)\//.test(String(url)) ? local(url) : url, options);
   window.EventSource = function (url) { return new OriginalSource(String(url).startsWith('https://ninjabacker.com/') ? local(url) : url); };
   window.ninjaTips = []; window.ninjaChat = [];
   window.processIncomingMessage = data => { if (data.type === 'ninjabacker') ninjaTips.push(data); return originalProcess(data); };
   window.sendMessageToTabs = data => ninjaChat.push(data);
  }, { port, receiverPort });
  await request({ cmd: 'setOnOffState', data: { value: true } });
  await bg.evaluate(() => initTransport(streamID, password));
  await main.locator('[data-page=streams]').click();
  await popup.evaluate(() => { document.getElementById('monetization-settings').open = true; applyPopupBeginnerMode(false); });
  await popup.waitForFunction(() => document.getElementById('money-current').textContent.includes('Load your wishlist'));
  await popup.locator('#money-mode').selectOption('ninja');
  await popup.locator('#money-ninja-username').fill('creator');
  await popup.locator('#money-ninja-token').fill(token);
  await popup.locator('#money-ninja-enabled').check();
  await popup.locator('#money-ninja-qr').check();
  await popup.locator('#money-save').click();
  await popup.waitForFunction(() => document.getElementById('money-status').textContent === 'Saved.');
  await bg.waitForFunction(async () => (await handleMonetizationRequest({ action: 'get' })).status === 'Listening for tips');
  const state = await request({ cmd: 'monetization', action: 'get' });
  assert(state.tokenSaved && !JSON.stringify(state).includes(token));
  assert(!(await popup.locator('#money-overlay').getAttribute('href')).includes(token));
  assert.equal(await popup.locator('#money-ninja-token').inputValue(), '');
  const windowPromise = app.waitForEvent('window');
  await app.evaluate(({ BrowserWindow }, url) => new BrowserWindow({ show: false, width: 800, height: 600, webPreferences: { offscreen: true, backgroundThrottling: false } }).loadURL(url), 'file:///' + root + '/monetization.html?session=' + room + '&mode=ninja');
  const overlay = await windowPromise;
  await overlay.waitForLoadState();
  await overlay.locator('#support-card').waitFor({ state: 'visible', timeout: 25000 });
  assert.equal(await overlay.locator('#qr').getAttribute('title'), 'https://ninjabacker.com/creator');
  const preview = await server.inject({ method: 'POST', url: '/v1/tip/test', headers: { authorization: 'Bearer ' + session.token } });
  assert.equal(preview.statusCode, 200);
  await overlay.waitForFunction(() => document.getElementById('title').textContent === 'Test tip received');
  assert.equal(await bg.evaluate(() => ninjaTips.length), 0);
  await overlay.screenshot({ path: path.join(os.tmpdir(), 'ssn-ninja-test.png'), omitBackground: true });
  const tip = db.createTip({ performerId: owner.id, amount: 500, currency: 'JPY', tipperName: 'Private identity', message: '<img src=x onerror=alert(1)> Thanks!', anonymous: true, callbackId: 'caller-controlled' });
  const payload = JSON.stringify({ id: 'evt_ssn_fixture', type: 'payment_intent.succeeded', livemode: true, created: Math.floor(Date.now() / 1000) - 3600, account: owner.stripe_account_id, data: { object: { id: 'pi_ssn_fixture', amount: 500, currency: 'jpy', metadata: { tipId: tip.id, performerId: owner.id } } } });
  const delivery = { method: 'POST', url: '/v1/webhook/stripe', payload, headers: { 'content-type': 'application/json', 'stripe-signature': stripe.webhooks.generateTestHeaderString({ payload, secret: process.env.STRIPE_WEBHOOK_SECRET }) } };
  assert.equal((await server.inject(delivery)).statusCode, 200);
  await bg.waitForFunction(() => ninjaTips.length === 1);
  const received = await bg.evaluate(() => ninjaTips[0]);
  assert.equal(received.donoValue, 500);
  assert.equal(received.chatname, 'Anonymous');
  assert(received.textonly);
  assert(!JSON.stringify(received).includes('caller-controlled'));
  assert(!JSON.stringify(received).includes('Private identity'));
  assert.equal((await server.inject(delivery)).json().duplicate, true);
  await overlay.waitForFunction(() => document.getElementById('title').textContent.startsWith('Anonymous tipped'));
  assert.equal(await overlay.locator('#detail img').count(), 0);
  await overlay.screenshot({ path: path.join(os.tmpdir(), 'ssn-ninja-tip.png'), omitBackground: true });
  await overlay.setViewportSize({ width: 390, height: 600 });
  assert(await overlay.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await overlay.screenshot({ path: path.join(os.tmpdir(), 'ssn-ninja-mobile.png'), omitBackground: true });
  assert.equal(await bg.evaluate(() => ninjaTips.length), 1);
  assert.equal(await bg.evaluate(() => ninjaChat.length), 0);
  await popup.locator('#monetization-settings').screenshot({ path: path.join(os.tmpdir(), 'ssn-ninja-popup.png') });
  const secret = 'c'.repeat(64);
  await popup.locator('#money-ninja-delivery').selectOption('reliable');
  await popup.locator('#money-ninja-secret').fill(secret);
  await popup.locator('#money-save').click();
  await popup.waitForFunction(() => !!document.getElementById('money-ninja-webhook').value);
  const hook = new URL(await popup.locator('#money-ninja-webhook').inputValue()).pathname;
  assert.equal(await popup.locator('#money-ninja-secret').inputValue(), '');
  const setup = await request({ cmd: 'monetization', action: 'get' });
  assert(!JSON.stringify(setup).includes(secret));
  async function webhook(id, isTest, invalid = false) {
   const body = JSON.stringify({ type: 'tip', amount: 9, currency: 'USD', name: 'Webhook Viewer', message: 'Queued while offline', timestamp: 123, isTest });
   const t = String(Math.floor(Date.now() / 1000));
   return receiver.inject({ method: 'POST', url: hook, headers: { 'content-type': 'application/json', 'x-ninjabacker-delivery': id, 'x-ninjabacker-signature': 't=' + t + ',v1=' + (invalid ? '0'.repeat(64) : crypto.createHmac('sha256', secret).update(t + '.').update(body).digest('hex')) }, payload: body });
  }
  assert.equal((await webhook('bad', false, true)).statusCode, 401);
  await request({ cmd: 'setOnOffState', data: { value: false } });
  assert.equal((await webhook('offline', false)).statusCode, 204);
  assert.equal((await webhook('preview', true)).statusCode, 204);
  assert.equal(await bg.evaluate(() => ninjaTips.length), 1);
  await receiver.close(); receiverDb.close(); await startReceiver();
  assert.equal((await webhook('offline', false)).statusCode, 204);
  await request({ cmd: 'setOnOffState', data: { value: true } });
  await bg.waitForFunction(() => ninjaTips.length === 2);
  assert.equal(await bg.evaluate(() => ninjaTips[1].chatname), 'Webhook Viewer');
  assert.equal(await bg.evaluate(() => ninjaTips[1].donoValue), 9);
  await popup.waitForFunction(() => document.getElementById('money-ninja-status').textContent === 'Reliable delivery connected');
  assert.equal(receiverDb.prepare('SELECT count(*) AS n FROM ninja_deliveries WHERE ack=1').get().n, 2);
  assert.equal((await webhook('offline', false)).statusCode, 204);
  await overlay.waitForFunction(() => document.getElementById('title').textContent.startsWith('Webhook Viewer tipped'));
  await app.evaluate(({ BrowserWindow }, url) => { const w = BrowserWindow.getAllWindows().find(w => w.webContents.getURL() === url); w.setSize(1584, 1600); }, main.url());
  await main.waitForTimeout(500);
  await popup.locator('#money-ninja-reliable-panel').scrollIntoViewIfNeeded();
  console.log('Receiver panel geometry:', await popup.evaluate(() => { const e = document.getElementById('money-ninja-reliable-panel'); return { width: e.clientWidth, content: e.scrollWidth, input: document.getElementById('money-ninja-webhook').getBoundingClientRect().width }; }));
  await popup.locator('#monetization-settings').screenshot({ path: path.join(os.tmpdir(), 'ssn-ninja-reliable-popup.png') });
  assert.equal(await bg.evaluate(() => ninjaTips.length), 2);
  assert.equal(await bg.evaluate(() => ninjaChat.length), 0);
  await popup.locator('#money-ninja-delivery').selectOption('live');
  await popup.locator('#money-save').click();
  await popup.waitForFunction(() => !document.getElementById('money-ninja-webhook').value);
  assert.equal(receiverDb.prepare('SELECT count(*) AS n FROM ninja_receivers').get().n, 0);
  await popup.locator('#money-ninja-enabled').uncheck();
  await popup.locator('#money-save').click();
  await overlay.locator('#support-card').waitFor({ state: 'hidden' });
  console.log('PASS: actual NinjaBacker source -> SSE -> SSApp -> overlay; private Tip ID setup, safe test preview, JPY units, anonymous/plain text, delayed signed payment retry, deduplication, QR/mobile, disable, reliable signed delivery, offline/server-restart recovery, test isolation, acknowledgments, switch back to live and no chat sends.');
 } finally {
  if (app) await app.close();
  await receiver.close(); receiverDb.close();
  await server.close();
  db.default.close();
 }
})().catch(error => { console.error(error); process.exitCode = 1; });
