(function(){
const H='https://joystick.tv',WSH='wss://joystick.tv/cable',ID=JSON.stringify({channel:'GatewayChannel'});
try{if(window.__SSN_JOYSTICK_WS_LOADED__)return;window.__SSN_JOYSTICK_WS_LOADED__=true;}catch(_){ }
const CK='joystickWsConfig',TK='joystickWsTokens',AK='joystickAuthMethod',SK='joystickOAuthState';
const els={
 cid:document.getElementById('client-id'),sec:document.getElementById('client-secret'),slug:document.getElementById('channel-slug'),chid:document.getElementById('channel-id'),
 redir:document.getElementById('redirect-uri'),code:document.getElementById('auth-code'),save:document.getElementById('save-config'),start:document.getElementById('start-auth'),
 ex:document.getElementById('exchange-code'),rf:document.getElementById('refresh-token'),clr:document.getElementById('clear-auth'),con:document.getElementById('connect-btn'),
 dis:document.getElementById('disconnect-btn'),ar:document.getElementById('auto-reconnect'),schip:document.getElementById('socket-chip'),achip:document.getElementById('auth-chip'),
 cchip:document.getElementById('channel-chip'),status:document.getElementById('status-text'),feed:document.getElementById('feed'),log:document.getElementById('log'),
 input:document.getElementById('chat-input'),send:document.getElementById('send-btn'),method:document.getElementById('auth-method-selector')
};
const st={cfg:{clientId:'',clientSecret:'',channelSlug:'',channelId:'',redirectUri:'',autoReconnect:true,authMethod:'external'},tokens:null,socket:null,sub:false,map:{},settings:{},rt:null,tt:null};
const R={CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3};
const wsProxy={readyState:R.CLOSED,close:()=>disconnect(true),send:(raw)=>{if(!raw)return;let t=''+raw;let i=t.indexOf(' :');send(i>=0?t.slice(i+2):t,true).catch(()=>{});}};
try{window.websocket=wsProxy;}catch(_){ }
const ext=()=>typeof chrome!=='undefined'&&chrome&&chrome.runtime&&typeof chrome.runtime.sendMessage==='function';
const esc=(v)=>{v=v==null?'':String(v);if(st.settings&&st.settings.textonlymode)return v;return v.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');};
const slug=v=>(v?String(v).trim().replace(/^@+/,'').toLowerCase():'');
const strip=(v)=>{if(!v||typeof v!=='string')return '';const d=document.createElement('div');d.innerHTML=v.replace(/<[^>]*>/g,' ');return (d.textContent||'').replace(/\s+/g,' ').trim();};
const pjson=v=>{if(!v)return null; if(typeof v==='object')return v; try{return JSON.parse(String(v));}catch(_){return null;}};
const b64=v=>{try{return btoa(unescape(encodeURIComponent(v)));}catch(_){return btoa(v);}};
const now=()=>new Date().toLocaleTimeString();
const defaultRedirect=()=>{const h=String(window.location.href||'').split('#')[0].split('?')[0];if(window.location.origin&&window.location.origin!=='null')return `${window.location.origin}${window.location.pathname}`;return h||window.location.pathname||'';};
const line=(p,html)=>{if(!p)return;const d=document.createElement('div');d.className='entry';d.innerHTML=html;p.appendChild(d);while(p.children.length>250)p.removeChild(p.firstChild);p.scrollTop=p.scrollHeight;};
const log=(m,l='info')=>{let c='#89b6ff';if(l==='error')c='#ff9eaa';else if(l==='warn')c='#ffd983';else if(l==='success')c='#81f2d7';line(els.log,`<div class="meta" style="color:${c};">${now()} [${l.toUpperCase()}]</div><div>${esc(m||'')}</div>`);};
const feed=(n,m,meta='')=>line(els.feed,`<div class="meta">${now()} ${esc(meta)}</div><div><span class="name">${esc(n)}</span>${esc(m)}</div>`);
const relay=(o)=>{if(!o||typeof o!=='object')return;try{if(ext()&&chrome.runtime.id){chrome.runtime.sendMessage(chrome.runtime.id,o,()=>{});return;}}catch(_){ }
 try{if(window.ninjafy&&typeof window.ninjafy.sendMessage==='function'){window.ninjafy.sendMessage(null,o,null,typeof window.__SSAPP_TAB_ID__!=='undefined'?window.__SSAPP_TAB_ID__:null);return;}}catch(_){ }
 try{const f=Object.assign({},o);if(typeof window.__SSAPP_TAB_ID__!=='undefined')f.__tabID__=window.__SSAPP_TAB_ID__;window.postMessage(f,'*');}catch(_){ }};
const wss=(s,m,e={})=>relay({wssStatus:Object.assign({platform:'joystick',status:String(s||''),message:m||''},e||{})});
function setStatus(s,msg=''){if(els.status)els.status.textContent=msg; if(!els.schip)return;els.schip.className='chip'; if(s==='connected')els.schip.classList.add('good'); else if(s==='connecting')els.schip.classList.add('warn'); else els.schip.classList.add('bad'); els.schip.textContent=`Socket: ${s}`;}
function setAuth(){if(!els.achip)return;els.achip.className='chip'; if(st.tokens&&st.tokens.access_token){els.achip.classList.add('good');els.achip.textContent='Token: authorized';}else{els.achip.classList.add('warn');els.achip.textContent='Token: not authorized';}}
function setChannel(){if(!els.cchip)return;els.cchip.className='chip';const s=(st.cfg.channelSlug||'').trim(),c=(st.cfg.channelId||'').trim();if(s||c){els.cchip.classList.add('good');els.cchip.textContent=`Channel: ${s?`@${s}`:''}${s&&c?' / ':''}${c||''}`;}else els.cchip.textContent='Channel: unknown';}
function syncCfg(){st.cfg.clientId=(els.cid?.value||'').trim();st.cfg.clientSecret=(els.sec?.value||'').trim();st.cfg.channelSlug=slug(els.slug?.value||'');st.cfg.channelId=(els.chid?.value||'').trim();st.cfg.redirectUri=(els.redir?.value||'').trim()||defaultRedirect();st.cfg.autoReconnect=!!els.ar?.checked;const r=els.method?.querySelector('input[name="joystick-auth-method"]:checked');if(r)st.cfg.authMethod=r.value;try{localStorage.setItem(CK,JSON.stringify(st.cfg));localStorage.setItem(AK,st.cfg.authMethod||'external');}catch(_){ }setChannel();}
function applyCfg(){if(els.cid)els.cid.value=st.cfg.clientId||'';if(els.sec)els.sec.value=st.cfg.clientSecret||'';if(els.slug)els.slug.value=st.cfg.channelSlug||'';if(els.chid)els.chid.value=st.cfg.channelId||'';if(els.redir)els.redir.value=st.cfg.redirectUri||'';if(els.ar)els.ar.checked=st.cfg.autoReconnect!==false; if(els.method){const show=!!(new URLSearchParams(location.search).has('ssapp')||(window.ninjafy&&typeof window.ninjafy.startJoystickOAuth==='function')||(window.__ssapp&&typeof window.__ssapp.startJoystickOAuth==='function')); els.method.classList.toggle('hidden',!show);els.method.querySelectorAll('input[name="joystick-auth-method"]').forEach(x=>x.checked=x.value===st.cfg.authMethod);}setChannel();}
function loadCfg(){try{const j=JSON.parse(localStorage.getItem(CK)||'{}');if(j&&typeof j==='object')Object.assign(st.cfg,j);}catch(_){ }
 try{const m=localStorage.getItem(AK);if(m==='external'||m==='local')st.cfg.authMethod=m;}catch(_){ }
 const q=new URLSearchParams(location.search),h=new URLSearchParams(location.hash.slice(1));const ch=q.get('channel')||q.get('username')||h.get('channel')||h.get('username');const cid=q.get('channel_id')||q.get('channelId')||h.get('channel_id')||h.get('channelId');const c=q.get('client_id')||h.get('client_id');const r=q.get('redirect_uri')||h.get('redirect_uri');const a=q.get('autoreconnect')||h.get('autoreconnect');
 if(ch)st.cfg.channelSlug=slug(ch); if(cid)st.cfg.channelId=String(cid).trim(); if(c)st.cfg.clientId=String(c).trim(); if(r)st.cfg.redirectUri=String(r).trim(); if(a!=null)st.cfg.autoReconnect=a!=='0'; if(!st.cfg.redirectUri)st.cfg.redirectUri=defaultRedirect();
}
function saveTokens(){if(st.tokens&&st.tokens.access_token){try{localStorage.setItem(TK,JSON.stringify(st.tokens));}catch(_){ }}else{try{localStorage.removeItem(TK);}catch(_){ }}setAuth();}
function loadTokens(){try{const t=JSON.parse(localStorage.getItem(TK)||'null');st.tokens=t&&t.access_token?t:null;}catch(_){st.tokens=null;}setAuth();}
function scheduleRefresh(){if(st.tt){clearTimeout(st.tt);st.tt=null;} if(!st.tokens||!st.tokens.refresh_token||!st.tokens.expires_at)return; const d=Math.max(5000,Number(st.tokens.expires_at)-Date.now()-60000); st.tt=setTimeout(()=>refreshToken().catch(e=>log(`Token refresh failed: ${e.message||e}`,'error')),d);}
async function exchange(code){syncCfg();code=(code||'').trim(); if(!st.cfg.clientId||!st.cfg.clientSecret)throw new Error('Client ID and Client Secret are required for token exchange.'); if(!code)throw new Error('Authorization code is required.');
 const p=new URLSearchParams();p.set('redirect_uri',st.cfg.redirectUri||'/unused');p.set('code',code);p.set('grant_type','authorization_code');
 const r=await fetch(`${H}/api/oauth/token?${p.toString()}`,{method:'POST',headers:{Authorization:`Basic ${b64(`${st.cfg.clientId}:${st.cfg.clientSecret}`)}`,Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:''});
 const tx=await r.text();let j={};try{j=tx?JSON.parse(tx):{};}catch(_){j={error:tx};}
 if(!r.ok||!j.access_token)throw new Error(j.error||j.error_description||`Token exchange failed (HTTP ${r.status})`);
 st.tokens={access_token:j.access_token,token_type:j.token_type||'Bearer',refresh_token:j.refresh_token||'',expires_at:j.expires_in?Date.now()+Number(j.expires_in)*1000:null};saveTokens();scheduleRefresh();wss('authorized','Joystick OAuth token acquired');log('OAuth token exchange succeeded.','success');if(els.code)els.code.value='';await loadStreamSettings().catch(()=>{});
}
async function refreshToken(){syncCfg(); if(!st.cfg.clientId||!st.cfg.clientSecret)throw new Error('Client ID and Client Secret are required for refresh.'); if(!st.tokens||!st.tokens.refresh_token)throw new Error('No refresh token available.');
 const p=new URLSearchParams();p.set('refresh_token',st.tokens.refresh_token);p.set('grant_type','refresh_token');
 const r=await fetch(`${H}/api/oauth/token?${p.toString()}`,{method:'POST',headers:{Authorization:`Basic ${b64(`${st.cfg.clientId}:${st.cfg.clientSecret}`)}`,Accept:'application/json','Content-Type':'application/x-www-form-urlencoded'},body:''});
 const tx=await r.text();let j={};try{j=tx?JSON.parse(tx):{};}catch(_){j={error:tx};}
 if(!r.ok||!j.access_token)throw new Error(j.error||j.error_description||`Token refresh failed (HTTP ${r.status})`);
 st.tokens={access_token:j.access_token,token_type:j.token_type||st.tokens.token_type||'Bearer',refresh_token:j.refresh_token||st.tokens.refresh_token||'',expires_at:j.expires_in?Date.now()+Number(j.expires_in)*1000:null};saveTokens();scheduleRefresh();wss('authorized','Joystick token refreshed');log('OAuth token refreshed.','success');
}
async function loadStreamSettings(){if(!st.tokens||!st.tokens.access_token)return null;const r=await fetch(`${H}/api/users/stream-settings`,{headers:{Authorization:`Bearer ${st.tokens.access_token}`,Accept:'application/json','Content-Type':'application/json'}});const tx=await r.text();let j={};try{j=tx?JSON.parse(tx):{};}catch(_){ }
 if(!r.ok){log(j.error||j.error_description||`Stream settings fetch failed (HTTP ${r.status})`,'warn');return null;} const s=slug(j.username||st.cfg.channelSlug||''); const c=j.channel_id!=null?String(j.channel_id).trim():''; if(s)st.cfg.channelSlug=s;if(c)st.cfg.channelId=c;applyCfg();syncCfg();log(`Stream settings loaded${s?` for @${s}`:''}${c?` (channel ${c})`:''}.`,'success');return j;}
function allowMsg(m){if(!m||typeof m!=='object')return false;const cid=m.channelId!=null?String(m.channelId).trim():'';const ms=slug(m?.streamer?.slug||m?.streamer?.username||m?.author?.slug||m?.author?.username||'');if(cid&&ms)st.map[cid]=ms;const fs=slug(st.cfg.channelSlug||''),fc=(st.cfg.channelId||'').trim();
 if(fc)return cid===fc; if(fs){if(ms)return ms===fs; if(cid&&st.map[cid])return slug(st.map[cid])===fs; return false;} if(cid&&!st.cfg.channelId){st.cfg.channelId=cid;if(ms&&!st.cfg.channelSlug)st.cfg.channelSlug=ms;applyCfg();syncCfg();log(`Auto-selected channel ${st.cfg.channelId}${st.cfg.channelSlug?` (@${st.cfg.channelSlug})`:''}.`,'success');} return true;
}
function normalize(m){const e=String(m?.event||'').toLowerCase(),t=String(m?.type||'').toLowerCase();if(e==='chatmessage'||t==='new_message'){const a=m.author&&typeof m.author==='object'?m.author:{};const n=strip(a.displayNameWithFlair||'')||a.displayName||a.username||a.slug||'Joystick User';return {platform:'joystick',type:'joystick',chatname:esc(n),chatmessage:esc((m.text||'').trim()),chatimg:a.signedPhotoThumbUrl||a.signedPhotoUrl||'',chatbadges:[a.isStreamer?'Streamer':'',a.isModerator?'Moderator':'',a.isSubscriber?'Subscriber':''].filter(Boolean),nameColor:a.usernameColor||'',hasDonation:'',membership:a.isSubscriber?'Subscriber':'',textonly:!!(st.settings&&st.settings.textonlymode),userid:a.slug||a.username||'',meta:{rawEvent:m.event||'ChatMessage',rawType:m.type||'',messageId:m.messageId||'',channelId:m.channelId||'',visibility:m.visibility||'',botCommand:m.botCommand||'',botCommandArg:m.botCommandArg||'',mention:!!m.mention,mentionedUsername:m.mentionedUsername||'',highlight:!!m.highlight,createdAt:m.createdAt||'',streamer:m.streamer&&typeof m.streamer==='object'?{slug:m.streamer.slug||'',username:m.streamer.username||''}:null}};}
 if(e==='userpresence'){if(st.settings&&st.settings.hideevents)return null;let ev='presence',msg=String(m.text||'').trim();if(t==='enter_stream'){ev='user_enter';if(!msg)msg='User entered stream';}else if(t==='leave_stream'){ev='user_leave';if(!msg)msg='User left stream';}return {platform:'joystick',type:'joystick',event:ev,chatname:'Joystick',chatmessage:esc(msg),chatimg:'',hasDonation:'',membership:'',textonly:!!(st.settings&&st.settings.textonlymode),meta:{rawEvent:m.event||'UserPresence',rawType:m.type||'',channelId:m.channelId||'',createdAt:m.createdAt||''}};}
 const md=pjson(m.metadata);let amt=null,dono='';if(md&&typeof md==='object'){if(md.how_much!=null&&Number.isFinite(Number(md.how_much)))amt=Number(md.how_much);else if(md.amount!=null&&Number.isFinite(Number(md.amount)))amt=Number(md.amount);if(amt!=null)dono=`${amt} tokens`;}if(!dono&&typeof m.text==='string'){const x=m.text.match(/(\d+)\s*token/i);if(x&&x[1]){dono=`${x[1]} tokens`;amt=Number(x[1]);}}
 let ev=t||e||'event';if(t==='started'||t==='streamresuming')ev='stream_online';else if(t==='ended'||t==='streamending')ev='stream_offline';else if(t==='followed')ev='new_follower';else if(t==='tipped'||t==='tipmenu')ev='donation';
 return {platform:'joystick',type:'joystick',event:ev,chatname:'Joystick',chatmessage:esc(strip(String(m.text||''))||String(m.type||m.event||'Joystick event')),chatimg:'',hasDonation:dono,membership:'',textonly:!!(st.settings&&st.settings.textonlymode),meta:{rawEvent:m.event||'',rawType:m.type||'',channelId:m.channelId||'',createdAt:m.createdAt||'',metadata:md||null,amount:amt}};
}
function onMsg(m,p){if(!allowMsg(m))return;const n=normalize(m);if(!n)return;st.cfg.channelId=st.cfg.channelId||String(m.channelId||'').trim();if(st.cfg.channelId&&!st.cfg.channelSlug){const s=slug(m?.streamer?.slug||m?.streamer?.username||m?.author?.slug||m?.author?.username||'');if(s)st.cfg.channelSlug=s;}setChannel();
 st._c=(st._c||0)+1;feed(n.event?`${n.chatname||'Joystick'} (${n.event})`:(n.chatname||'Joystick'),strip(String(n.chatmessage||''))||'[event]',`#${st._c}`);relay({message:n});if(n.event==='new_follower')wss('info','Follower event received',{channelId:String(m.channelId||'')});if(p&&p.identifier)log(`Gateway message: ${m.event||m.type||'event'} (${m.channelId||'unknown channel'})`,'info');
}
function socketUrl(){return `${WSH}?token=${encodeURIComponent(b64(`${st.cfg.clientId}:${st.cfg.clientSecret}`))}`;}
function reconnect(r=''){if(st.rt){clearTimeout(st.rt);st.rt=null;} if(!st.cfg.autoReconnect||!st.cfg.clientId||!st.cfg.clientSecret)return;st.rt=setTimeout(()=>connect().catch(e=>log(`Reconnect failed: ${e.message||e}`,'error')),5000);log(`Reconnect scheduled in 5s${r?` (${r})`:''}.`,'warn');}
async function connect(){syncCfg(); if(!st.cfg.clientId||!st.cfg.clientSecret)throw new Error('Client ID and Client Secret are required.'); if(st.socket&&(st.socket.readyState===WebSocket.OPEN||st.socket.readyState===WebSocket.CONNECTING))return; if(st.rt){clearTimeout(st.rt);st.rt=null;}
 setStatus('connecting','Connecting to Joystick websocket...');wss('connecting','Connecting to Joystick websocket');wsProxy.readyState=R.CONNECTING;const s=new WebSocket(socketUrl(),['actioncable-v1-json']);st.socket=s;st.sub=false;
 s.addEventListener('open',()=>{log('Socket opened. Subscribing to GatewayChannel.','success');setStatus('connecting','Socket open. Waiting for subscription confirmation...');wss('connecting','Socket opened, subscribing');try{s.send(JSON.stringify({command:'subscribe',identifier:ID}));}catch(e){log(`Subscribe send failed: ${e.message||e}`,'error');}});
 s.addEventListener('message',(e)=>{let p;try{p=JSON.parse(e.data);}catch(err){log(`Invalid socket message: ${err.message||err}`,'warn');return;} if(!p||typeof p!=='object'||p.type==='ping')return; if(p.type==='confirm_subscription'){st.sub=true;setStatus('connected','Connected and subscribed to GatewayChannel.');wss('connected','Subscribed to Joystick GatewayChannel');wsProxy.readyState=R.OPEN;return;} if(p.type==='reject_subscription'){setStatus('error','GatewayChannel subscription rejected. Check bot credentials.');wss('error','Gateway subscription rejected');log('Gateway subscription rejected.','error');return;} if(p.message)onMsg(p.message,p);});
 s.addEventListener('close',(e)=>{const c=Number.isFinite(e.code)?e.code:0,r=e.reason||'';st.socket=null;st.sub=false;wsProxy.readyState=R.CLOSED;setStatus('disconnected',`Socket closed${c?` (${c})`:''}${r?`: ${r}`:''}`);wss('disconnected','Joystick websocket closed',{code:c,reason:r});log(`Socket closed${c?` (${c})`:''}${r?`: ${r}`:''}.`,c===1000?'info':'warn');if(c!==1000)reconnect('socket closed');});
 s.addEventListener('error',()=>{setStatus('error','Socket error. Check credentials/network.');wss('error','Joystick websocket error');log('Socket error.','error');});
}
function disconnect(manual){if(st.rt){clearTimeout(st.rt);st.rt=null;} const s=st.socket;st.socket=null;st.sub=false; if(s){try{s.close(1000,manual?'manual_disconnect':'disconnect');}catch(_){ }} wsProxy.readyState=R.CLOSED;setStatus('disconnected',manual?'Disconnected.':'Connection reset.');wss('disconnected',manual?'Manual disconnect':'Disconnected');}
async function send(text,silent){text=(text||'').trim();if(!text)throw new Error('Chat message is empty.');syncCfg();if(!st.socket||st.socket.readyState!==WebSocket.OPEN||!st.sub)throw new Error('Socket is not connected/subscribed.');if(!st.cfg.channelId)throw new Error('Channel ID is required before sending chat. Wait for auto-detection or enter it manually.');
 st.socket.send(JSON.stringify({command:'message',identifier:ID,data:JSON.stringify({action:'send_message',text,channelId:st.cfg.channelId})}));if(!silent){feed('You (bot)',text,'outbound');log(`Sent chat message to channel ${st.cfg.channelId}.`,'success');}}
function authUrl(){syncCfg();if(!st.cfg.clientId)throw new Error('Client ID is required.');const sn=`${Math.random().toString(36).slice(2,12)}${Date.now().toString(36).slice(-6)}`;try{localStorage.setItem(SK,sn);}catch(_){ }
 const p=new URLSearchParams();p.set('response_type','code');p.set('client_id',st.cfg.clientId);p.set('scope','bot');p.set('state',sn);if(st.cfg.redirectUri)p.set('redirect_uri',st.cfg.redirectUri);return `${H}/api/oauth/authorize?${p.toString()}`;}
async function extAuth(){const fn=(window.ninjafy&&typeof window.ninjafy.startJoystickOAuth==='function')?window.ninjafy.startJoystickOAuth:((window.__ssapp&&typeof window.__ssapp.startJoystickOAuth==='function')?window.__ssapp.startJoystickOAuth:null);
 if(!fn){window.open(authUrl(),'_blank');log('Opened Joystick authorize URL in external browser tab.','info');return;}syncCfg();if(!st.cfg.clientId)throw new Error('Client ID is required.');const r=await fn({clientId:st.cfg.clientId,scopes:['bot'],redirectUri:st.cfg.redirectUri||defaultRedirect()});
 if(!r)throw new Error('No OAuth result returned.'); if(r.code){if(els.code)els.code.value=r.code;log('Received OAuth code from external helper. Exchange it now.','success');return;} if(r.access_token){st.tokens={access_token:r.access_token,token_type:r.token_type||'Bearer',refresh_token:r.refresh_token||'',expires_at:r.expires_in?Date.now()+Number(r.expires_in)*1000:null};saveTokens();scheduleRefresh();log('Received token from external helper.','success');return;} throw new Error(r.error||'OAuth flow did not provide code/token.');
}
function bridge(){if(ext()){try{chrome.runtime.onMessage.addListener((req,s,cb)=>{try{if(req==='getSource'){cb('joystick');return;}if(req==='focusChat'){if(els.input){els.input.focus();cb(true);return;}cb(false);return;}if(req&&typeof req==='object'){if(req.settings){st.settings=req.settings;cb(true);return;}if(req.type==='SEND_MESSAGE'&&typeof req.message==='string'){send(req.message,false).then(()=>cb(true)).catch(e=>{log(`SEND_MESSAGE failed: ${e.message||e}`,'error');cb(false);});return true;}}}catch(e){log(`Extension bridge error: ${e.message||e}`,'error');}cb(false);});}catch(e){log(`Failed wiring extension bridge: ${e.message||e}`,'warn');}
 try{chrome.runtime.sendMessage(chrome.runtime.id,{getSettings:true},(r)=>{if(chrome.runtime.lastError)return;if(r&&r.settings)st.settings=r.settings;});}catch(_){ }}
 window.addEventListener('message',(ev)=>{if(!ev||!ev.data||typeof ev.data!=='object')return;let req=ev.data;if(req.__ssappSendToTab)req=req.__ssappSendToTab;if(req&&req.type==='SEND_MESSAGE'&&typeof req.message==='string'){send(req.message,false).catch(e=>log(`postMessage SEND_MESSAGE failed: ${e.message||e}`,'error'));}});
}
function bind(){els.save?.addEventListener('click',()=>{syncCfg();applyCfg();setAuth();log('Configuration saved.','success');if(els.status)els.status.textContent='Configuration saved.';});els.ar?.addEventListener('change',()=>syncCfg());els.method?.querySelectorAll('input[name="joystick-auth-method"]').forEach(r=>r.addEventListener('change',()=>syncCfg()));
 els.start?.addEventListener('click',async()=>{try{syncCfg();if(!st.cfg.clientId)throw new Error('Client ID is required.');if((new URLSearchParams(location.search).has('ssapp')||(window.ninjafy&&typeof window.ninjafy.startJoystickOAuth==='function')||(window.__ssapp&&typeof window.__ssapp.startJoystickOAuth==='function'))&&st.cfg.authMethod==='external'){await extAuth();if(els.status)els.status.textContent='Started external auth flow.';return;}location.href=authUrl();}catch(e){log(`Auth start failed: ${e.message||e}`,'error');if(els.status)els.status.textContent=`Auth start failed: ${e.message||e}`;}});
 els.ex?.addEventListener('click',()=>exchange(els.code?.value||'').catch(e=>{log(`Code exchange failed: ${e.message||e}`,'error');if(els.status)els.status.textContent=`Code exchange failed: ${e.message||e}`;}));
 els.rf?.addEventListener('click',()=>refreshToken().catch(e=>{log(`Refresh failed: ${e.message||e}`,'error');if(els.status)els.status.textContent=`Refresh failed: ${e.message||e}`;}));
 els.clr?.addEventListener('click',()=>{st.tokens=null;saveTokens();log('Cleared OAuth tokens.','warn');if(els.status)els.status.textContent='OAuth tokens cleared.';wss('signin_required','OAuth token cleared');});
 els.con?.addEventListener('click',()=>connect().catch(e=>{log(`Connect failed: ${e.message||e}`,'error');if(els.status)els.status.textContent=`Connect failed: ${e.message||e}`;wss('error',e.message||String(e));setStatus('error');}));
 els.dis?.addEventListener('click',()=>disconnect(true));
 els.send?.addEventListener('click',()=>send(els.input?.value||'',false).then(()=>{if(els.input)els.input.value='';}).catch(e=>{log(`Send failed: ${e.message||e}`,'error');if(els.status)els.status.textContent=`Send failed: ${e.message||e}`;}));
 els.input?.addEventListener('keydown',(e)=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();els.send?.click();}});
}
function boot(){loadCfg();loadTokens();applyCfg();setAuth();setStatus('disconnected');bind();bridge();const q=new URLSearchParams(location.search);const code=q.get('code'),ret=q.get('state'),exp=localStorage.getItem(SK)||'';if(code&&(!exp||!ret||exp===ret)){try{const u=new URL(location.href);u.searchParams.delete('code');u.searchParams.delete('state');history.replaceState({},document.title,u.toString());}catch(_){ }if(els.code)els.code.value=code;exchange(code).catch(e=>log(`Auto exchange failed: ${e.message||e}`,'error'));}
 if(st.tokens&&st.tokens.access_token){scheduleRefresh();loadStreamSettings().catch(()=>{});}if(st.cfg.clientId&&st.cfg.clientSecret){if(els.status)els.status.textContent='Ready. Connect websocket when you are ready.';}else{if(els.status)els.status.textContent='Enter your Joystick bot Client ID/Secret, then connect.';wss('signin_required','Joystick bot credentials required');}
 try{window.__SSAPP_START_JOYSTICK_AUTH__=()=>{if(st.cfg.authMethod==='external')return extAuth();location.href=authUrl();return Promise.resolve();};}catch(_){ }
 window.addEventListener('beforeunload',()=>disconnect(false));
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
